language: python
sudo: false # use container based build
notifications:
  email: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION --file=ci/requirements-${TRAVIS_PYTHON_VERSION}.txt
  - source activate test-env
  - export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/home/travis/miniconda/envs/test-environment/lib
  - conda install -c https://conda.anaconda.org/ioos nco
  - python setup.py install

# command to run tests
script:
  - ncks --version
  - python -c "from nco import Nco"
  - py.test
